name: check_norminette
run-name: ${{ github.actor }} is checking norminette
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  checking_norminette:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
      - uses: actions/checkout@v4
      - run: |
          ls -la
          echo ""
          git branch -a
